### ISSUE TITLE
Wrap but not scroll?

### ISSUE THREAD

**Issue by karlkfi** [chris17453/ttygif#2]
When making a recording I get unexpected behavior where new characters added to the bottom right (on a long line, spread across multiple asciicast json lines) are wrapped to the bottom left, overwriting the characters already there.

I would expect a scroll up to happen when it wraps, so it's writing over whitespace instead of the previous line of text.

I can't tell from the readme whether this is auto wrap (DECAWM) mode or not... it seems to wrap but not scroll.

I also can't tell from the readme how exactly I'm supposed to enable or disable auto wrap when reading in from an asciicast file. Do I need to modify every line of the asciicast? Can a flag be added to toggle it for all lines? Can the default be made to behave like asciinema play?

**Comment by chris17453** [comment]
Hey,

If you can send me the cast file. And ill debug.

-C

**Comment by karlkfi** [comment]
I figured out the issue while trying to create a minimal example.

The problem is that my asciicast file has extra carriage returns (\r) without line breaks (\n) in several places. I'm still not sure why asciinema added those carriage returns (maybe wrapping in the original recording terminal?), but if I remove all the extra carriage returns, the gif is rendered correctly in ttygif.

I suspect when playing in my terminal, via asciinema play, the carriage returns were just being ignored without a linebreak.

So the problem probably lies with asciinema rec.

**Comment by chris17453** [comment]
Ok, cool. I've been off this project for a while. I'm about 90% done rewriting it in c. Though I'd like to account for the odd carriage returns in this edition as well.

I'll try and get the most recent version pushed this week.

-C

**Comment by karlkfi** [comment]
FWIW, I still had a graphical defect I couldn't figure out. 

Now instead of the whole line wrapping around on itself (which seems like intended behavior for a carriage return without a line break), I had one character that would wrap on the same line and then the next would be on the next line, as if the carriage return and line break were separated by a character.

The only thing I can come up with is that this is related to my automated recording method, which reads a file and pipes characters over STDOUT to asciinema,  with a sleep for a fraction of a second between each character. So each line in the asciicast is effectively a single character except for prompts and STDOUT/STDERR from executed commands.

**Comment by chris17453** [comment]
Can you send me an example file? It can be anything generic, like ls output
or cat'ing a file.

I've got an idea of what this might be but need some test data.

I think the issue might lie in the sequence generation which is
separated by timestamp.


-C
